### ISSUE TITLE
Add CI Runs

### ISSUE THREAD

**Issue by COM8** [AP-Sensing/ostree-tui#18]
### Description

As a developer I want continuous feedback on my code if it works and still fulfils all coding standards defined in the project.
Also building on multiple OS and dependency versions is complex and error prone if done manually, we need an automated version to check for it.

**Solution:** Add CI runs.

### Acceptance Criteria
- [ ] Add a CI run that builds using gcc as compiler a debug build
- [ ] Add a CI run that builds using gcc as compiler a release build
- [ ] Add a CI run that builds using clang as compiler a debug build
- [ ] Add a CI run that builds using clang as compiler a release build
- [ ] Run a clang-tidy build in debug
- [ ] Run a clang-format check
- [ ] All CI runs have to be run under [`fedora:latest`](https://hub.docker.com/_/fedora)
- [ ] Optionally add cppcheck
- [ ] Investigate if CI builds using sanitizers make sense e.g. thread-, address-, undefined behaviour-, ...

### References 
Take a look at cpr: https://github.com/libcpr/cpr/tree/master/.github/workflows

Here you can get a rough idea how to add a CI run in GitLab and what is required to do so for clang-tidy etc.

**Comment by forgottosave** [comment]
~Sadly, there is no Github runner for `fedora:latest` (or any other Linux runner than `ubuntu:...`), see~
- ~[declined issue requesting a fedora runner](https://github.com/actions/runner-images/issues/9520)~
- ~[supported Github runners](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories)~

~which is why I will have to use ubuntu:latest. Self-hosting a runner isn't viable for this project.~

Never mind, I'll use the same "workaround" as in cpr
